# Generated by Django 5.2.4 on 2025-07-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_category_remove_event_created_at_and_more'),
    ]

    operations = [
    ]
