# Generated by Django 5.2.4 on 2025-07-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
