# Generated by Django 5.2.4 on 2025-07-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_booking_razorpay_order_id_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
