# Generated by Django 5.2.4 on 2025-07-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
