# Generated by Django 5.2.4 on 2025-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_participant_payment_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
