# Generated by Django 5.2.4 on 2025-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_booking_screenshot_payment_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
